In [ ]:
https://numpy.org/doc/stable/
    

행렬

행렬 그대로 데이터에 저장된다

# 면이 계속 겹쳐진다
면과 면이 만나 입체, 3차원

3차원 배열은 여러 개의 2차원 배열이 겹쳐져서 구성됩니다.
여기서 각각의 행과 열은 하나의 "면"을 이루며, 이러한 2차원 배열을 쌓아 올린 것이 3차원 배열입니다.

예를 들어, 직육면체는 3차원 도형입니다. 이 도형은 길이, 너비, 높이의 세 가지 차원을 가지고 있습니다. 이 세 가지 차원은 각각 X, Y, Z축으로 나타낼 수 있습니다.

알고리즘은 연산이다. 연산 위해 넘파이 쓰는거다. - 다차원 배열

문제를 푸는 것은 방정식을 만드는 것

y = xa + b
학습해서 a,b를 결정해줌 - 알고리즘에서 연산으로 해줌
그 학습 과정이 연산임
y예측
가중치, 절편 계속 바꿔 가면서 예측값 y구함
실제 y와 비교해서 계속 로직해서 학습해서 어떤 경우에 둘의 차이가 최소화가 되느냐
가중치 = 파라미터

넘파이 - 브로드캐스팅 - 다른 차원 간

행렬 - 모든 원소가 동일한 데이터 타입, 원소를 기준으로 하는 연산
datagframe은 원소 타입이 다를 수 있음(열마다), 열을 기준으로 이런저런 수행

대부분 행렬 간의 연산을 쓴다 - 알고리즘에서는
다차원이 연산할 때는 사용할 수 있다

차량 1 정보 - 행렬
차량 2 정보 - 행렬

#### 행렬의 필요성
- 현실 세계의 많은 문제는 행렬을 이용해서 해결할 수 있다
- 행렬로 해결할 수 없다면, 매우 어려운 문제일 수 있다
- 컴퓨터 사이언스의 가장 기본이 되는 개념
- 배열도 행렬 형태이다
- 수학의 매트릭스
- 데이터가 1개 이상이면 사실상 다 행렬로 표현할 수 있다 -> 장점
- 메모리 공간에 차례대로 올린 형태로 표현됨 (보이는 그대로)

1차원 배열 = 백터
2차원 배열 = 행렬
3차원 배열 = 텐서

일반적으로 데이터가 많으면 행렬로 표현한다라고 말한다

#### NumPy는 “Numerical Python“의 약자로 대규모 다차원 배열과 행렬 연산에 필요한 다양한 함수를 제공
* Numerical Python을 의미하는 NumPy는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
* 많은 머신러닝 알고리즘이 넘파이 기반으로 작성돼 있으며 알고리즘의 입출력 데이터를 넘파이 배열 타입으로 사용함
* 넘파이의 기본 데이터 타입은 ndarray. ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산 수행

NumPy 특징

- 강력한 N 차원 배열 객체
- 정교한 브로드케스팅(Broadcast) 기능
- C/C ++ 및 포트란 코드 통합 도구
- 유용한 선형 대수학, 푸리에 변환 및 난수 기능
- 푸리에 변환(Fourier transform, FT)은 시간이나 공간에 대한 함수를 시간 또는 공간 주파수 성분으로 분해하는 변환
- 범용적 데이터 처리에 사용 가능한 다차원 컨테이너

Numpy Documentation  

https://numpy.org/doc/1.21/index.html

Numpy는 대용량 데이터 배열을 효율적으로 다룰 수 있도록 설계되었다.
- Numpy는 내부적으로 데이터를 다른 내장 파이썬 객체와 구분된 연속된 메모리 블록에 저장
- Numpy의 각종 알고리즘은 모두 C로 작성되어 타입 검사나 다른 오버헤드 없이 메모리를 직접 조작
- Numpy 배열은 또한 내장 파이썬의 연속된 자료형들보다 훨씬 더 적은 메모리를 사용
- Numpy 연산은 파이썬 반복문을 사용하지 않고 전체 배열에 대한 복잡한 계산을 수행

# arange()

In [ ]:
# 지정된 범위 내에서 균등 간격의 값을 갖는 배열을 생성하는데 사용
# 연속된 값을 가진 1차원 배열을 생성
# start: 시작 값입니다. 생략하면 0이 됩니다.
# stop: 끝 값으로, 이 값은 생성되는 배열에 포함되지 않습니다. 필수 매개변수입니다.
# step: 값 사이의 간격을 나타내는 단계입니다. 생략하면 1이 됩니다.
# dtype: 배열 요소의 데이터 유형을 나타내는 문자열입니다. 예를 들어, 'int', 'float' 등이 될 수 있습니다.
# reshape: 배열의 모양을 변경할 수 있는 함수, 새 배열의 형상을 튜플로 지정함, numpy 배열 객체에 붙여 사용 가능

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# reshape()

In [ ]:
#  NumPy 패키지에 포함되어 있는 함수
# NumPy 배열 객체에서 사용할 수 있는 함수 중 하나
# 배열의 모양을 변경하는 데에 활용

import numpy as np
import pandas as pd

ar = np.arange(100).reshape(10,10)
df = pd.DataFrame(ar, columns = list('abcdefghij'))
df.iloc[2:5, 3:5] = np.nan
df.iloc[1:3, 1:3] = np.nan
df

    a     b     c     d     e   f   g   h   i   j
0   0   1.0   2.0   3.0   4.0   5   6   7   8   9
1  10   NaN   NaN  13.0  14.0  15  16  17  18  19
2  20   NaN   NaN   NaN   NaN  25  26  27  28  29
3  30  31.0  32.0   NaN   NaN  35  36  37  38  39
4  40  41.0  42.0   NaN   NaN  45  46  47  48  49
5  50  51.0  52.0  53.0  54.0  55  56  57  58  59
6  60  61.0  62.0  63.0  64.0  65  66  67  68  69
7  70  71.0  72.0  73.0  74.0  75  76  77  78  79
8  80  81.0  82.0  83.0  84.0  85  86  87  88  89
9  90  91.0  92.0  93.0  94.0  95  96  97  98  99

# isnull() - pandas library
- Pandas DataFrame과 Series 객체에서 결측치(null 값)을 찾기 위해 사용되는 메소드
- 해당 메소드는 각 요소에 대해서 null 값 여부를 True 또는 False로 반환

In [ ]:
import numpy as np
import pandas as pd

ar = np.arange(100).reshape(10,10)
df = pd.DataFrame(ar, columns = list('abcdefghij'))
df.iloc[2:5, 3:5] = np.nan
df.iloc[1:3, 1:3] = np.nan
df.isnull()

       a      b      c      d      e      f      g      h      i      j
0  False  False  False  False  False  False  False  False  False  False
1  False   True   True  False  False  False  False  False  False  False
2  False   True   True   True   True  False  False  False  False  False
3  False  False  False   True   True  False  False  False  False  False
4  False  False  False   True   True  False  False  False  False  False
5  False  False  False  False  False  False  False  False  False  False
6  False  False  False  False  False  False  False  False  False  False
7  False  False  False  False  False  False  False  False  False  False
8  False  False  False  False  False  False  False  False  False  False
9  False  False  False  False  False  False  False  False  False  False

In [ ]:
import numpy as np
import pandas as pd

ar = np.arange(100).reshape(10,10)
df = pd.DataFrame(ar, columns = list('abcdefghij'))
df.iloc[2:5, 3:5] = np.nan
df.iloc[1:3, 1:3] = np.nan
df.isnull().sum()

a    0
b    2
c    2
d    3
e    3
f    0
g    0
h    0
i    0
j    0
dtype: int64

# np.nan
- numpy 라이브러리에서 제공하는 상수(constant)
- Not A Number
- 'float' 자료형임 (해당 열이 다 float이 됨)

In [ ]:
import numpy as np
import pandas as pd

ar = np.arange(100).reshape(10,10)
df = pd.DataFrame(ar, columns = list('abcdefghij'))
df.iloc[2:5, 3:5] = np.nan
df.iloc[1:3, 1:3] = np.nan
df

    a     b     c     d     e   f   g   h   i   j
0   0   1.0   2.0   3.0   4.0   5   6   7   8   9
1  10   NaN   NaN  13.0  14.0  15  16  17  18  19
2  20   NaN   NaN   NaN   NaN  25  26  27  28  29
3  30  31.0  32.0   NaN   NaN  35  36  37  38  39
4  40  41.0  42.0   NaN   NaN  45  46  47  48  49
5  50  51.0  52.0  53.0  54.0  55  56  57  58  59
6  60  61.0  62.0  63.0  64.0  65  66  67  68  69
7  70  71.0  72.0  73.0  74.0  75  76  77  78  79
8  80  81.0  82.0  83.0  84.0  85  86  87  88  89
9  90  91.0  92.0  93.0  94.0  95  96  97  98  99

# sum() - built-in function
- numpy, pandas에서도 제공함(내장 함수가 더 범용적)
- iterable 객체(리스트, 튜플, 배열 등)의 원소들을 모두 더한 값을 반환
- iterable은 요소를 하나씩 반환 가능한 객체를 의미합니다.(list, tuple, set, dictionary, string 등)
- iterable 객체는 for 반복문에서 사용될 수 있습니다.

In [ ]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10): my_array2 = my_arr * 2

Wall time: 0 ns

In [ ]:
import pandas as pd

data = pd.Series([1, 2, 3, 4, 5])
print(data.sum())

15

In [ ]:
import pandas as pd

data = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]})
print(data.sum())
data

A     6
B    15
C    24
dtype: int64

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [ ]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

Wall time: 690 ms

In [ ]:
# 배열 연산 
# randn() - 평균이 0이고 분산이 1인 표준 정규 분포(Standard Normal Distribution)를 따르는
# 난수(random number)를 생성하는 함수

np.random.seed(0)    # 시드값 설정
data = np.random.randn(2,3)    # 2행 3열의 정규분포를 random으로 뽑아줌
print(data, '\n')
print(data * 10, '\n')
print(data + data)

[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]]

[[17.64052346  4.00157208  9.78737984]
 [22.40893199 18.6755799  -9.7727788 ]]

[[ 3.52810469  0.80031442  1.95747597]
 [ 4.4817864   3.73511598 -1.95455576]]

In [ ]:
# 데이터 크기 보기

print(data.shape)   # 크기
print(data.dtype)   # 자료형
print(data.ndim)    # 차원

(2, 3)
float64
2

In [ ]:
# 배열 생성
# array() - list -> array로
# 1차원
# n - dimensional (n차원) array라는 뜻

data1 = [6,7,5,8,0,1]
arr1 = np.array(data1)
print(arr1, type(arr1))

[6 7 5 8 0 1] <class 'numpy.ndarray'>

In [ ]:
# 2차원

data2 = [[1,2,3,4,], [5,6,7,8]]
arr2 = np.array(data2)
print(arr2, type(arr2))
print(arr2.shape, '\n')
print(arr2.ndim, '\n')
print(arr2.dtype)

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>
(2, 4)

2

int64

In [ ]:
# 3차원

data3 = [[[1,2,3,4,5],[6,7,8,9,10]],
         [[1,2,3,4,5],[6,7,8,9,10]],
         [[1,2,3,4,5],[6,7,8,9,10]]]

arr3 = np.array(data3)

print(arr3, type(arr3))
print(arr3.shape, '\n')
print(arr3.ndim, '\n')
print(arr3.dtype)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]] <class 'numpy.ndarray'>
(3, 2, 5)

3

int64

배열 생성 및 초기화
- Numpy는 원하는 shape로 배열을 설정하고 각 요소를 특정 값으로 초기화하는 zeros, ones, full, eye 함수 제공
- 파라미터로 입력한 배열과 같은 shape의 배열을 만드는 zeros_like, ones_like, full_like 함수도 제공

In [ ]:
print(np.zeros(10),'\n')
print(np.zeros((3,5)),'\n')
print(np.zeros((2,3,2)),'\n')   # 숫자 순서 - 2개라는 의미 3행 2열이

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]

In [ ]:
print(np.ones(10),'\n')
print(np.ones((3,5)),'\n')
print(np.ones((2,3,2)),'\n')

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]

In [ ]:
# [과제] zeros_like, ones_like, full_like 함수 사용 예를 작성하세요.

a = np.arange(10).reshape(2,5)
print(a,'\n')

print(np.zeros_like(a),'\n')
print(np.ones_like(a),'\n')
print(np.full_like(a, 777))

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[0 0 0 0 0]
 [0 0 0 0 0]]

[[1 1 1 1 1]
 [1 1 1 1 1]]

[[777 777 777 777 777]
 [777 777 777 777 777]]

In [ ]:
# arrang 함수 : 파이썬의 range 함수의 배열 버전
ar = np.arange(15)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# reshape 함수
ar.reshape(1,15)    # 2차원임

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [ ]:
ar.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
# Q. array1에 reshape 함수를 이용 (5,2) 배열을 생성하고 형태를 같이 출력하세요.
array1 = np.arange(10)
array1.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
# Q. ar에 reshape() 함수 이용,  1차원 2차원, 3차원 배열 생성
ar = np.arange(12)
print(ar.reshape(12), '\n')
print(ar.reshape(3,4), '\n')
print(ar.reshape(2,3,2))

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

In [ ]:
# 차원 변경
import numpy as np

ar1 = np.arange(30)
print('1 -> 2,3차원')
ar11 = ar1.reshape(2,15)
ar12 = ar1.reshape(2,-1)
ar13 = ar1.reshape(-1,2,5)
print(ar11,'\n')
print(ar12,'\n')
print(ar13)

1 -> 2,3차원
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]

In [ ]:
print('2 -> 1,3차원')
print(ar12, '\n')
ar21 = ar12.reshape(-1,)    # 1차원시는 튜플처럼 사용함 유의
ar23 = ar12.reshape(-1,2,5)
print(ar21,'\n')
print(ar23)

2 -> 1,3차원
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]

In [ ]:
print('3 -> 1,2차원')
ar31 = ar13.reshape(-1,)
ar32 = ar13.reshape(3,-1)
print(ar31,'\n')
print(ar32)

3 -> 1,2차원
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]

In [ ]:
# reshape()를 바로 붙여 쓸 수도 있고, tolist()로 array -> list 가능

ar3 = np.arange(30).reshape(3,2,5)
print(ar3, type(ar3), '\n')
l3 = ar3.tolist()
print(l3, type(l3))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] <class 'numpy.ndarray'>

[[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]], [[10, 11, 12, 13, 14], [15, 16, 17, 18, 19]], [[20, 21, 22, 23, 24], [25, 26, 27, 28, 29]]] <class 'list'>

행렬의 종류

https://math-development-geometry.tistory.com/52

- 정방행렬은 행과 열의 수가 같은 행렬 (행렬방정식의 기본이 되는 행렬. 차수가 n)
- 대각행렬은 주대각선 원소를 제외한 모든 원소들이 0인 정방행렬
- 삼각행렬은 주대각선 원소를 기준으로 위 또는 아래에 있는 성분이 모두 0인 정방행렬
- 항등행렬은 행렬 곱셈 연산에 항등원으로 작용하는 행렬 (주대각선 성분이 모두1인 정방행렬) (= 단위 행렬)
- 영행렬은 모든 원소가 0인 행렬로 곱셈 연산에서 영원으로 작용하는 행렬
- 전치행렬은 주대각선 원소를 기준으로 행과 열을 바꿔주는 행렬
- 직교행렬은 행렬 A의 역행렬이 A의 전치행렬이고 A의 전치행렬과 A 행렬을 곱하였을때 항등행렬이 나오는 행렬

### 행렬을 알아야 그에 맞게 
### matrix는 면을 포함한 다차원 배열임

- 항등행렬은 정방행렬이다(O)
- 정방행렬은 항등행렬이다(X) - 주대각선 성분이 모두 1이 아닐 수 있으니까


- 항등행렬은 대각행렬이다(0)
- 대각행렬은 항등행렬이다(X) - 주대각선 원소가 1이 아니어도 되니까

In [ ]:
# 정방행렬

a = np.full((2,2), 7)
a

array([[7, 7],
       [7, 7]])

In [ ]:
# 항등행렬 (= 단위행렬)
# eye() - 주어진 크기의 단위 행렬(identity matrix)을 생성하는 함수

ar = np.eye(3)  # 정방행렬이어야 하니까, 3x3임
ar

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 대각행렬
# diag() - 정방행렬(square matrix)에서 대각선 상의 원소만 추출하여 1차원 배열로 반환하거나,
# 주어진 1차원 배열을 대각선 원소로 갖는 정방행렬을 생성함

diag_mat = np.diag([1,2,3,4,5])
diag_mat

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [ ]:
# 삼각행렬
# triu() - 주어진 배열에서 상삼각행렬(upper-triangle matrix)을 추출하는 함수

upper_tri_mat = np.triu([[1,2,3],[4,5,6],[7,8,9]])
print(upper_tri_mat)

[[1 2 3]
 [0 5 6]
 [0 0 9]]

#### [과제]하삼각행렬을 생성하세요.

In [ ]:
# trill() - 주어진 배열에서 하삼각행렬(lower-triangle matrix)을 추출하는 함수

lower_tri_mat = np.tril([[1,2,3],[4,5,6],[7,8,9]])
print(lower_tri_mat)

[[1 0 0]
 [4 5 0]
 [7 8 9]]

In [ ]:
# 전치행렬
.T

mat = np.array([[1,2], [3,4], [5,6]])
print(mat,'\n')

transpose_mat = mat.T
transpose_mat

[[1 2]
 [3 4]
 [5 6]]

array([[1, 3, 5],
       [2, 4, 6]])

#### # 직교행렬
- 행과 열이 서로 직교하는 정방행렬
- 모든 열벡터와 행벡터가 서로 직교하고 크기가 1인 단위백터로 이루어짐
- np.linalg.qr() 함수를 사용하여 QR 분해를 수행하여 직교행렬을 추출
- q를 추출하여 직교행렬 orth_mat을 만든다
- np.dot(orth_mat, orth_mat.T)를 계산하여 직교성을 검증
- np.allclose() 함수로 두 행렬이 동일한지 검사. True를 반환하면 두 행렬은 동일

In [ ]:
# 직교행렬은 행렬 A의 역행렬이 A의 전치행렬이고 A의 전치행렬과 A 행렬을 곱하였을때 항등행렬이 나오는 행렬

mat = np.random.randn(3,3)
print(mat,'\n')

# qr 분해
q,r = np.linalg.qr(mat)

# 직교행렬 추출
orth_mat = q
print(orth_mat,'\n')

# 직교성 검증
print(np.allclose(np.dot(orth_mat, orth_mat.T), np.eye(3)))    # np.dot(orth_mat, orth_mat.T)과 np.eye(3)이 동일한지 검증

[[-0.80325646 -1.05259417  0.2732104 ]
 [ 0.7333857  -2.98657464  1.55165253]
 [-0.64891016 -0.66243683  1.37887514]]

[[-0.63420607 -0.47906725 -0.6068585 ]
 [ 0.57904006 -0.81442286  0.03778904]
 [-0.51234293 -0.32742934  0.79391105]]

True

In [ ]:
# 인덱싱, 슬라이싱
ar2 = np.arange(1,10).reshape(3,3)
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(ar2[2])
print(ar2[0,2])
print(ar2[0][2])

[7 8 9]
3
3

In [ ]:
ar = np.arange(20).reshape(5,4)
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
ar[:2, 1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
# Q. ar에서 슬라이싱을 사용해서 아래와 같이 출력하세요.
ar = np.arange(1,10).reshape(3,3)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(ar[:2, :2],'\n')

print(ar[1:, :],'\n')
print(ar[1:],'\n')

print(ar,'\n')

print(ar[:2, 1:],'\n')

print(ar[:2, 0])

[[1 2]
 [4 5]]

[[4 5 6]
 [7 8 9]]

[[4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2 3]
 [5 6]]

[1 4]

#### [과제] ar에서 인덱스를 이용해서 값을 선택하고 리스트로 아래와 같이 출력하세요.

In [ ]:
ar = np.arange(1,10).reshape(3,3)

print(list(ar[:2, 2]))
print(ar[:2, :2].tolist())
print(ar[:2].tolist())

[3, 6]
[[1, 2], [4, 5]]
[[1, 2, 3], [4, 5, 6]]

In [ ]:
# Boolean indexing
ar = np.arange(1,10)
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ar[ar > 5]

array([6, 7, 8, 9])

In [ ]:
# Q. 1 ~14까지 ndarray를 만들어 array_e로 저장하고 (array_e / 2) >5를 만족하는 값을 불린 인덱스로 출력하세요.
# 원하는 것만 뽑을 수 있어서 유용한 방식임

array_e = np.arange(1,15)
array_e[(array_e /2) > 5]

array([11, 12, 13, 14])

In [ ]:
# arr에서 0.5보다 큰 수를 출력하세요.
np.random.seed(0)
arr = np.random.randn(30)
print(arr, '\n')

arr[arr > 0.5]

[ 0.12877045 -0.02506291  0.89582886  1.42291172  0.68630178 -0.64209268
 -0.98773115 -1.21034319 -0.82150293 -0.10303316 -0.0725293  -2.75701427
 -1.35770443 -0.49897895  2.61111742  1.94297524 -0.13854571  0.09312665
  0.55821101 -1.07212536  0.84393677 -1.37976149  0.16657196 -0.60292683
  0.12646296 -0.77952773 -0.40235293 -0.542997    0.31479747  0.61685905]

array([0.89582886, 1.42291172, 0.68630178, 2.61111742, 1.94297524,
       0.55821101, 0.84393677, 0.61685905])

In [ ]:
# data에서 3의 배수만 출력하세요.

np.random.seed(0)
data = np.arange(30)

data1 = data[1:]
data1[data1 %3 == 0]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

[과제] [1,2,0,0,4,0]에서 zero가 아닌 인덱스를 배열 형태로 출력하세요.<br><br>

np.where(condition)은 
- condition 배열의 요소가 True인 인덱스를 반환하는 함수입니다. 
- condition 배열은 bool 타입이어야 하며, 반환값은 tuple 타입으로 (array of row indices, array of column indices)의 형태로 반환

In [ ]:
arr = np.array([1, 2, 3,], [4, 5, 6], [7, 8, 9])

In [ ]:
# np.where() 반환값은 튜플 형태임

import numpy as np

a = np.array([1,2,0,0,4,0])

index=np.where(a!=0)
print(index)
print(index[0])

(array([0, 1, 4], dtype=int64),)
[0 1 4]

In [ ]:
# nonzero() - 배열에서 0이 아닌 원소의 인덱스를 반환하는 NumPy의 함수

a = np.array([1,2,0,0,4,0])
nz = np.nonzero(a)
nz[0]

array([0, 1, 4], dtype=int64)

In [ ]:
bools = np.array([False, False, True, True])
bools

array([False, False,  True,  True])

In [ ]:
bools.any()

True

In [ ]:
bools.all()

False

In [ ]:
# Q. arr에서 0보다 크면 2, 아니면 -2로 변경하세요.
# where() - 조건에 따라 배열의 값을 선택하는 데 사용되는 함수

arr = np.random.randn(4,4)

np.where(arr > 0, 2, -2)

array([[ 2, -2,  2, -2],
       [-2,  2,  2, -2],
       [ 2, -2,  2, -2],
       [ 2,  2,  2,  2]])

In [ ]:
# Q. arr의 모든 양수를 2로 바꾸세요.

arr = np.random.randn(4,4)

np.where(arr > 0 , 2, arr)

array([[-0.88778575, -1.98079647, -0.34791215,  2.        ],
       [ 2.        ,  2.        , -0.38732682, -0.30230275],
       [-1.04855297, -1.42001794, -1.70627019,  2.        ],
       [-0.50965218, -0.4380743 , -1.25279536,  2.        ]])

In [ ]:
# np.sort() : 복사본을 반환
np.random.seed(0)
arr = np.random.randint(1,100, size=10)
arr

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88])

In [ ]:
print(np.sort(arr))
print(arr)

[10 22 37 45 48 65 68 68 84 88]
[45 48 65 68 68 10 84 22 37 88]

In [ ]:
sorted = np.sort(arr)
print(sorted)

[10 22 37 45 48 65 68 68 84 88]

In [ ]:
# 행렬이 2차원 이상일 경우 axis 축 값 설정을 통해 로우 방향, 칼럼 방향으로 정렬 수행

ar2 = np.array([[8,12],
               [7,1]])
               
print(ar2, '\n')
print(np.sort(ar2, axis=0), '\n')
print(np.sort(ar2, axis=1))    # default가 열 방향 (axis=1)

[[ 8 12]
 [ 7  1]]

[[ 7  1]
 [ 8 12]]

[[ 8 12]
 [ 1  7]]

In [ ]:
# ndarray.sort() : 원본 반영
# np.sort() - NumPy 라이브러리에서 제공되는 함수이며, 배열을 오름차순으로 정렬합니다.
# sort() - Python의 내장 함수인 list 객체에서 제공되는 메서드, 리스트를 오름차순으로 정렬합니다.

arr = np.random.randint(10, size=10)
print(arr)
arr.sort()
arr

[4 5 5 6 8 4 1 4 9 8]

array([1, 4, 4, 4, 5, 5, 6, 8, 8, 9])

In [ ]:
# randint() - 정수 하나 출력?

arr = np.random.randint(10, size=(10,10))
arr

array([[6, 1, 6, 7, 2, 3, 1, 9, 5, 9],
       [9, 2, 0, 9, 1, 9, 0, 6, 0, 4],
       [8, 4, 3, 3, 8, 8, 7, 0, 3, 8],
       [7, 7, 1, 8, 4, 7, 0, 4, 9, 0],
       [6, 4, 2, 4, 6, 3, 3, 7, 8, 5],
       [0, 8, 5, 4, 7, 4, 1, 3, 3, 9],
       [2, 5, 2, 3, 5, 7, 2, 7, 1, 6],
       [5, 0, 0, 3, 1, 9, 9, 6, 6, 7],
       [8, 8, 7, 0, 8, 6, 8, 9, 8, 3],
       [6, 1, 7, 4, 9, 2, 0, 8, 2, 7]])

In [ ]:
# 다차원 배열의 정렬은 sort 메서드에 넘긴 축에 따라 1차원 부분을 정렬
# np.sort()에서는 axis 썼는데, 여기서는 괄호 안에 숫자 넣어줌

arr.sort(1)
# arr.sort(0)   # 행방향
# arr.sort(1)     # 열방향. Default (1)
arr

array([[1, 1, 2, 3, 5, 6, 6, 7, 9, 9],
       [0, 0, 0, 1, 2, 4, 6, 9, 9, 9],
       [0, 3, 3, 3, 4, 7, 8, 8, 8, 8],
       [0, 0, 1, 4, 4, 7, 7, 7, 8, 9],
       [2, 3, 3, 4, 4, 5, 6, 6, 7, 8],
       [0, 1, 3, 3, 4, 4, 5, 7, 8, 9],
       [1, 2, 2, 2, 3, 5, 5, 6, 7, 7],
       [0, 0, 1, 3, 5, 6, 6, 7, 9, 9],
       [0, 3, 6, 7, 8, 8, 8, 8, 8, 9],
       [0, 1, 2, 2, 4, 6, 7, 7, 8, 9]])

In [ ]:
# 정렬된 행렬의 인덱스 반환 : 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때
# argsort() - 

org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(org_array)

sort_indices

[3 1 9 5]

array([1, 0, 3, 2])

In [ ]:
# 배열 데이터의 입출력
# np.save, np.load는 바이너리 형식 .npy 파일로 저장

arr = np.arange(10)
np.save('some_array', arr)

np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# np.savez : 여러 개의 배열을 압축된 형식으로 저장
import numpy as np

np.savez('array_archive', a=arr, b=arr)
arch = np.load('array_archive.npz')
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Q. 인덱싱을 사용하여 [1 0 1 0 1 0 1 0 1 0]를 출력하세요

a = np.ones(10, dtype=int)
a[[1,3,5,7,9]] = 0
print(a)

[1 0 1 0 1 0 1 0 1 0]

In [ ]:
[과제] 1 ~ 100을 아래와 같이 출력하세요

[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]] <class 'numpy.ndarray'>

In [ ]:
import numpy as np

array = np.arange(1, 101).reshape(10,10)

array[1] = sorted(array[1], reverse = True)
array[3] = sorted(array[3], reverse = True)
array[5] = sorted(array[5], reverse = True)
array[7] = sorted(array[7], reverse = True)
array[9] = sorted(array[9], reverse = True)

print(array)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]

In [ ]:
arr = np.arange(1,101).reshape(10,10)
arr[1::2] = arr[1::2, ::-1]
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 20,  19,  18,  17,  16,  15,  14,  13,  12,  11],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 40,  39,  38,  37,  36,  35,  34,  33,  32,  31],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 60,  59,  58,  57,  56,  55,  54,  53,  52,  51],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 80,  79,  78,  77,  76,  75,  74,  73,  72,  71],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [100,  99,  98,  97,  96,  95,  94,  93,  92,  91]])

In [ ]:
[과제] np.ones((10,10))을 아래와 같이 출력하세요

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
array = np.ones((10,10))
array[1:9, 1:9] = 0
array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
[과제] np.ones((5,5))을 아래와 같이 출력하세요

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
array = np.ones((5,5))
array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
[과제] np.zeros((8,8))을 이용해서 아래와 같이 출력하세요(두가지 방식:인덱싱, tile 함수)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
array = np.zeros((8,8))
array = array.astype(int)

array[0,[1,3,5,7]] = 1
array[1,[0,2,4,6]] = 1
array[2,[1,3,5,7]] = 1
array[3,[0,2,4,6]] = 1
array[4,[1,3,5,7]] = 1
array[5,[0,2,4,6]] = 1
array[6,[1,3,5,7]] = 1
array[7,[0,2,4,6]] = 1

array

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
[과제] np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55]],

       [[ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111]],

       [[112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165, 166, 167]],

       [[168, 169, 170, 171, 172, 173, 174, 175],
        [176, 177, 178, 179, 180, 181, 182, 183],
        [184, 185, 186, 187, 188, 189, 190, 191],
        [192, 193, 194, 195, 196, 197, 198, 199],
        [200, 201, 202, 203, 204, 205, 206, 207],
        [208, 209, 210, 211, 212, 213, 214, 215],
        [216, 217, 218, 219, 220, 221, 222, 223]],

       [[224, 225, 226, 227, 228, 229, 230, 231],
        [232, 233, 234, 235, 236, 237, 238, 239],
        [240, 241, 242, 243, 244, 245, 246, 247],
        [248, 249, 250, 251, 252, 253, 254, 255],
        [256, 257, 258, 259, 260, 261, 262, 263],
        [264, 265, 266, 267, 268, 269, 270, 271],
        [272, 273, 274, 275, 276, 277, 278, 279]],

       [[280, 281, 282, 283, 284, 285, 286, 287],
        [288, 289, 290, 291, 292, 293, 294, 295],
        [296, 297, 298, 299, 300, 301, 302, 303],
        [304, 305, 306, 307, 308, 309, 310, 311],
        [312, 313, 314, 315, 316, 317, 318, 319],
        [320, 321, 322, 323, 324, 325, 326, 327],
        [328, 329, 330, 331, 332, 333, 334, 335]]])

In [ ]:
(1, 5, 3)